-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, U.GENDER, 
    COUNT(DISTINCT U.USER_ID) AS USERS 
FROM ONLINE_SALE O, USER_INFO U
WHERE U.GENDER IS NOT NULL AND U.USER_ID=O.USER_ID
GROUP BY YEAR(O.SALES_DATE),MONTH(O.SALES_DATE),U.GENDER
ORDER BY YEAR(O.SALES_DATE),MONTH(O.SALES_DATE),U.GENDER;