-- 코드를 입력하세요
SELECT A.ANIMAL_ID ANIMAL_ID, A.ANIMAL_TYPE ANIMAL_TYPE, A.NAME NAME FROM ANIMAL_INS A
INNER JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE 
((A.SEX_UPON_INTAKE = 'Intact Male' OR A.SEX_UPON_INTAKE='Intact Female')
AND
(B.SEX_UPON_OUTCOME LIKE 'Spayed%' OR B.SEX_UPON_OUTCOME LIKE 'Neutered%'))
ORDER BY A.ANIMAL_ID;