-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR
FROM
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JJ FROM JULY
    GROUP BY FLAVOR) AS J, FIRST_HALF
WHERE 
    FIRST_HALF.FLAVOR=J.FLAVOR
ORDER BY TOTAL_ORDER+JJ DESC
LIMIT 3;

-- 코드를 입력하세요
# SELECT FIRST_HALF.FLAVOR
# FROM
#     (SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER_JULY
#     FROM JULY
#     GROUP BY FLAVOR) as j,
#     FIRST_HALF
# WHERE
#     FIRST_HALF.FLAVOR = j.FLAVOR
# ORDER BY TOTAL_ORDER + TOTAL_ORDER_JULY DESC
# LIMIT 3