# # -- 코드를 입력하세요
# SELECT A.PRODUCT_CODE, (COUNT(B.PRODUCT_ID)*SUM(B.SALES_AMOUNT)*A.PRICE) AS SALES FROM PRODUCT AS A 
# RIGHT OUTER JOIN OFFLINE_SALE AS B 
# ON A.PRODUCT_ID=B.PRODUCT_ID
# GROUP BY A.PRODUCT_CODE
# ORDER BY SALES, A.PRODUCT_CODE;

# SELECT A.PRODUCT_CODE, B.PRODUCT_ID, B.SALES_AMOUNT FROM PRODUCT AS A 
# RIGHT OUTER JOIN OFFLINE_SALE AS B 
# ON A.PRODUCT_ID=B.PRODUCT_ID
# GROUP BY A.PRODUCT_CODE
# ORDER BY B.PRODUCT_ID;

SELECT P.PRODUCT_CODE, (P.PRICE * SUM(O.SALES_AMOUNT)) AS SALES
FROM PRODUCT P
JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC