-- 코드를 입력하세요
# SELECT A.PRODUCT_CODE, (SUM(B.SALES_AMOUNT)*A.PRICE) AS SALES FROM PRODUCT AS A 
# RIGHT OUTER JOIN OFFLINE_SALE AS B 
# ON A.PRODUCT_ID=B.PRODUCT_ID
# GROUP BY A.PRODUCT_CODE
# ORDER BY SALES DESC, A.PRODUCT_CODE;

# SELECT A.PRODUCT_CODE, B.PRODUCT_ID, SUM(B.SALES_AMOUNT) FROM PRODUCT AS A 
# RIGHT OUTER JOIN OFFLINE_SALE AS B 
# ON A.PRODUCT_ID=B.PRODUCT_ID
# GROUP BY A.PRODUCT_CODE
# ORDER BY  A.PRODUCT_CODE;

SELECT P.PRODUCT_CODE AS PRODUCT_CODE, (SUM(O.SALES_AMOUNT)*P.PRICE) AS SALES
FROM PRODUCT P, OFFLINE_SALE O
WHERE P.PRODUCT_ID=O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC , P.PRODUCT_CODE ASC;