-- 코드를 입력하세요
SELECT B.BOOK_ID, A.AUTHOR_NAME, date_format(B.PUBLISHED_DATE, '%Y-%m-%d') FROM BOOK B
LEFT OUTER JOIN AUTHOR A
ON B.AUTHOR_ID=A.AUTHOR_ID
WHERE B.CATEGORY LIKE '경제'
ORDER BY PUBLISHED_DATE ASC;

